name: Build

on:
  push:
    tags:
      - "v*"

env:
  BUILD_TYPE: Release

jobs:
  linux-build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: build-appimage

    - name: Clone repo
      uses: actions/checkout@v2
      with:
        repository: brongo/Doom-Eternal-Model-Importer
        ref: main
        path: repo

    - name: Create missing directories
      run: |
        mkdir ${{github.workspace}}/app/usr/bin
        mkdir ${{github.workspace}}/app/usr/lib
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Build with CMake
      run: |
        export CC=gcc-10
        export CXX=g++-10
        cd ${{github.workspace}}/repo
        cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build build --config ${{env.BUILD_TYPE}}
        cp 'build/Doom Eternal Model Importer v1.2' ${{github.workspace}}/app/usr/bin/doom_eternal_model_importer
        cd ..

    - name: Turn into AppImage
      run: |
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        mv .git .gitbck
        ./linuxdeployqt-continuous-x86_64.AppImage ${{github.workspace}}/app/usr/share/applications/doom_eternal_model_importer.desktop -appimage -bundle-non-qt-libs
        mv .gitbck .git

    - name: Upload AppImage
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: '${{github.workspace}}/Doom Eternal Model Importer-*.AppImage'
